### PR TITLE
added shift-back functionality as well as couting keys down

### PR DESCRIPTION
**Pull request by myh1000**
I added the functionality to go forward with shift-backspace, as well as counting the numbers of keys down so, for example, tab-backspace, doesn't go back a page.

Also made the icons transparent

### CODE REVIEW

**Comment by stevensmith** [comment]
Thanks, was just about to add the shift+back combo also

**Comment by oslego** [comment]
Thank you for the contribution, @myh1000!

I like the addition of Shift+Backspace. It's a feature requested often. I'm not sure about the key counting, though. It seems to over-complicate the code for low yield. Readability is important so people can easily grasp the code and understand this extension isn't malicious.

Would you mind splitting your PR into individual tasks so I can merge the Shift+Backspace part?

I see you also bundled PNG icons. To be fair, I'd like to accept #1 on that since that's been introduced first.

Apologies for late reply. I've been away and disconnected for a while.

**Comment by myh1000** [comment]
I have to do some key counting because it only takes one key at a time, and I want to make sure that the only keys being pressed are the shift and backspace keys, nothing else.

**Comment by Etherealflux** [comment]
I was about to put in a PR for shift-back, but then realized this was already submitted ages ago. D'oh!

A simple check would be to make sure that alt and ctrl aren't being held down. It's a one-liner fix, plus curly braces. Should catch a decent number of mistakes, although I'm not sure what applications make heavy use of alt+backspace, really..

**Comment by myh1000** [comment]
You need the array to track which keys are being pressed down at the time, there is no held down key tracker.
Besides, if you only check for alt/ctrl, pressed other keys at the same time, like a, b, 4, etc. will still let the page to go back/forward, which is unintended.

**Comment by stevensmith** [comment]
Can't you just use event.shiftKey === true && event.keyCode === 8 to detect if shift was held down?

There's event.altKey and event.ctrlKey booleans also.

**Comment by myh1000** [comment]
The function is called by `document.onkeydown`, which calls it every time a key is pressed. Pressing two keys at the same time just calls the function two different times, so that statement will always evaluate as false.

**Comment by oslego** [comment]
@myh1000, as @stevensmith mentions, there is a Boolean property on the keydown event called `shiftKey` which is true if the Shift key is being pressed at the same time with the current key. No need to track a sequence of keys for this.

To add Forward behavior it's as simple as adding this this at the end of the file:

``` javascript
  e.preventDefault();
  if (e.shiftKey) {
    window.history.forward();
  } else {
    window.history.back();
  }
```

By that point at the end of the file, conditions have already filtered and you can be sure Backspace key is pressed and not in an input field.

Would you like to alter this PR or create a new one with that? I'd like to credit you with coming up with the feature (I don't use Forward, but many people do so it's going to be appreciated).

**Comment by oslego** [comment]
I went ahead and made the change to add Shift + Backspace functionality. People on Chrome Web Store were very anxious to have it.

Per @Etherealflux's suggestion, I also added guards for other modifiers (Ctrl, Meta, and Alt keys).

Thank you for work, @myh1000! I hope this won't discourage you from contributing in the future. Your energy spent on trying to fix this is very appreciated.

**Pull request closed without merging**
